// 国カード用の静的な国情報。
//   ja  : 日本語の通称（表示用）
//   iso2: ISO 3166-1 alpha-2（国旗画像 flagcdn.com 用・小文字）
//   wp  : 日本語版Wikipediaの記事名（省略時は ja をそのまま使う。
//         通称と記事名が違う国・曖昧な国だけ明示する）
// world-atlas countries-110m に含まれる国・地域のみ収録。

export interface CountryInfo {
  ja: string;
  iso2: string;
  wp?: string;
}

export const COUNTRY_INFO: Record<string, CountryInfo> = {
  AFG: { ja: "アフガニスタン", iso2: "af" },
  ALB: { ja: "アルバニア", iso2: "al" },
  DZA: { ja: "アルジェリア", iso2: "dz" },
  AGO: { ja: "アンゴラ", iso2: "ao" },
  AND: { ja: "アンドラ", iso2: "ad" },
  ATG: { ja: "アンティグア・バーブーダ", iso2: "ag" },
  ARG: { ja: "アルゼンチン", iso2: "ar" },
  ARM: { ja: "アルメニア", iso2: "am" },
  AUS: { ja: "オーストラリア", iso2: "au" },
  AUT: { ja: "オーストリア", iso2: "at" },
  AZE: { ja: "アゼルバイジャン", iso2: "az" },
  BHS: { ja: "バハマ", iso2: "bs" },
  BHR: { ja: "バーレーン", iso2: "bh" },
  BGD: { ja: "バングラデシュ", iso2: "bd" },
  BRB: { ja: "バルバドス", iso2: "bb" },
  BLR: { ja: "ベラルーシ", iso2: "by" },
  BEL: { ja: "ベルギー", iso2: "be" },
  BLZ: { ja: "ベリーズ", iso2: "bz" },
  BEN: { ja: "ベナン", iso2: "bj" },
  BTN: { ja: "ブータン", iso2: "bt" },
  BOL: { ja: "ボリビア", iso2: "bo" },
  BIH: { ja: "ボスニア・ヘルツェゴビナ", iso2: "ba" },
  BWA: { ja: "ボツワナ", iso2: "bw" },
  BRA: { ja: "ブラジル", iso2: "br" },
  BRN: { ja: "ブルネイ", iso2: "bn" },
  BGR: { ja: "ブルガリア", iso2: "bg" },
  BFA: { ja: "ブルキナファソ", iso2: "bf" },
  BDI: { ja: "ブルンジ", iso2: "bi" },
  KHM: { ja: "カンボジア", iso2: "kh" },
  CMR: { ja: "カメルーン", iso2: "cm" },
  CAN: { ja: "カナダ", iso2: "ca" },
  CAF: { ja: "中央アフリカ共和国", iso2: "cf" },
  TCD: { ja: "チャド", iso2: "td" },
  CHL: { ja: "チリ", iso2: "cl" },
  CHN: { ja: "中国", iso2: "cn", wp: "中華人民共和国" },
  COL: { ja: "コロンビア", iso2: "co" },
  COM: { ja: "コモロ", iso2: "km" },
  COG: { ja: "コンゴ共和国", iso2: "cg" },
  COD: { ja: "コンゴ民主共和国", iso2: "cd" },
  CRI: { ja: "コスタリカ", iso2: "cr" },
  CIV: { ja: "コートジボワール", iso2: "ci" },
  HRV: { ja: "クロアチア", iso2: "hr" },
  CUB: { ja: "キューバ", iso2: "cu" },
  CYP: { ja: "キプロス", iso2: "cy" },
  CZE: { ja: "チェコ", iso2: "cz" },
  DNK: { ja: "デンマーク", iso2: "dk" },
  DJI: { ja: "ジブチ", iso2: "dj" },
  DMA: { ja: "ドミニカ国", iso2: "dm" },
  DOM: { ja: "ドミニカ共和国", iso2: "do" },
  ECU: { ja: "エクアドル", iso2: "ec" },
  EGY: { ja: "エジプト", iso2: "eg" },
  SLV: { ja: "エルサルバドル", iso2: "sv" },
  GNQ: { ja: "赤道ギニア", iso2: "gq" },
  ERI: { ja: "エリトリア", iso2: "er" },
  EST: { ja: "エストニア", iso2: "ee" },
  ETH: { ja: "エチオピア", iso2: "et" },
  FLK: { ja: "フォークランド諸島", iso2: "fk" },
  FJI: { ja: "フィジー", iso2: "fj" },
  FIN: { ja: "フィンランド", iso2: "fi" },
  FRA: { ja: "フランス", iso2: "fr" },
  GAB: { ja: "ガボン", iso2: "ga" },
  GMB: { ja: "ガンビア", iso2: "gm" },
  GEO: { ja: "ジョージア", iso2: "ge", wp: "ジョージア (国)" },
  DEU: { ja: "ドイツ", iso2: "de" },
  GHA: { ja: "ガーナ", iso2: "gh" },
  GRC: { ja: "ギリシャ", iso2: "gr" },
  GRL: { ja: "グリーンランド", iso2: "gl" },
  GRD: { ja: "グレナダ", iso2: "gd" },
  GTM: { ja: "グアテマラ", iso2: "gt" },
  GIN: { ja: "ギニア", iso2: "gn" },
  GNB: { ja: "ギニアビサウ", iso2: "gw" },
  GUY: { ja: "ガイアナ", iso2: "gy" },
  HTI: { ja: "ハイチ", iso2: "ht" },
  HND: { ja: "ホンジュラス", iso2: "hn" },
  HUN: { ja: "ハンガリー", iso2: "hu" },
  ISL: { ja: "アイスランド", iso2: "is" },
  IND: { ja: "インド", iso2: "in" },
  IDN: { ja: "インドネシア", iso2: "id" },
  IRN: { ja: "イラン", iso2: "ir" },
  IRQ: { ja: "イラク", iso2: "iq" },
  IRL: { ja: "アイルランド", iso2: "ie" },
  ISR: { ja: "イスラエル", iso2: "il" },
  ITA: { ja: "イタリア", iso2: "it" },
  JAM: { ja: "ジャマイカ", iso2: "jm" },
  JPN: { ja: "日本", iso2: "jp" },
  JOR: { ja: "ヨルダン", iso2: "jo" },
  KAZ: { ja: "カザフスタン", iso2: "kz" },
  KEN: { ja: "ケニア", iso2: "ke" },
  KIR: { ja: "キリバス", iso2: "ki" },
  PRK: { ja: "北朝鮮", iso2: "kp", wp: "朝鮮民主主義人民共和国" },
  KOR: { ja: "韓国", iso2: "kr", wp: "大韓民国" },
  KWT: { ja: "クウェート", iso2: "kw" },
  KGZ: { ja: "キルギス", iso2: "kg" },
  LAO: { ja: "ラオス", iso2: "la" },
  LVA: { ja: "ラトビア", iso2: "lv" },
  LBN: { ja: "レバノン", iso2: "lb" },
  LSO: { ja: "レソト", iso2: "ls" },
  LBR: { ja: "リベリア", iso2: "lr" },
  LBY: { ja: "リビア", iso2: "ly" },
  LTU: { ja: "リトアニア", iso2: "lt" },
  LUX: { ja: "ルクセンブルク", iso2: "lu" },
  MDG: { ja: "マダガスカル", iso2: "mg" },
  MWI: { ja: "マラウイ", iso2: "mw" },
  MYS: { ja: "マレーシア", iso2: "my" },
  MDV: { ja: "モルディブ", iso2: "mv" },
  MLI: { ja: "マリ", iso2: "ml", wp: "マリ共和国" },
  MLT: { ja: "マルタ", iso2: "mt" },
  MRT: { ja: "モーリタニア", iso2: "mr" },
  MUS: { ja: "モーリシャス", iso2: "mu" },
  MEX: { ja: "メキシコ", iso2: "mx" },
  MNG: { ja: "モンゴル", iso2: "mn", wp: "モンゴル国" },
  MNE: { ja: "モンテネグロ", iso2: "me" },
  MAR: { ja: "モロッコ", iso2: "ma" },
  MOZ: { ja: "モザンビーク", iso2: "mz" },
  MMR: { ja: "ミャンマー", iso2: "mm" },
  NAM: { ja: "ナミビア", iso2: "na" },
  NPL: { ja: "ネパール", iso2: "np" },
  NLD: { ja: "オランダ", iso2: "nl" },
  NZL: { ja: "ニュージーランド", iso2: "nz" },
  NIC: { ja: "ニカラグア", iso2: "ni" },
  NER: { ja: "ニジェール", iso2: "ne" },
  NGA: { ja: "ナイジェリア", iso2: "ng" },
  NOR: { ja: "ノルウェー", iso2: "no" },
  OMN: { ja: "オマーン", iso2: "om" },
  PAK: { ja: "パキスタン", iso2: "pk" },
  PAN: { ja: "パナマ", iso2: "pa" },
  PNG: { ja: "パプアニューギニア", iso2: "pg" },
  PRY: { ja: "パラグアイ", iso2: "py" },
  PER: { ja: "ペルー", iso2: "pe" },
  PHL: { ja: "フィリピン", iso2: "ph" },
  POL: { ja: "ポーランド", iso2: "pl" },
  PRT: { ja: "ポルトガル", iso2: "pt" },
  QAT: { ja: "カタール", iso2: "qa" },
  ROU: { ja: "ルーマニア", iso2: "ro" },
  RUS: { ja: "ロシア", iso2: "ru" },
  RWA: { ja: "ルワンダ", iso2: "rw" },
  SAU: { ja: "サウジアラビア", iso2: "sa" },
  SEN: { ja: "セネガル", iso2: "sn" },
  SRB: { ja: "セルビア", iso2: "rs" },
  SLE: { ja: "シエラレオネ", iso2: "sl" },
  SGP: { ja: "シンガポール", iso2: "sg" },
  SVK: { ja: "スロバキア", iso2: "sk" },
  SVN: { ja: "スロベニア", iso2: "si" },
  SLB: { ja: "ソロモン諸島", iso2: "sb" },
  SOM: { ja: "ソマリア", iso2: "so" },
  ZAF: { ja: "南アフリカ", iso2: "za", wp: "南アフリカ共和国" },
  SSD: { ja: "南スーダン", iso2: "ss" },
  ESP: { ja: "スペイン", iso2: "es" },
  LKA: { ja: "スリランカ", iso2: "lk" },
  SDN: { ja: "スーダン", iso2: "sd" },
  SUR: { ja: "スリナム", iso2: "sr" },
  SWZ: { ja: "エスワティニ", iso2: "sz" },
  SWE: { ja: "スウェーデン", iso2: "se" },
  CHE: { ja: "スイス", iso2: "ch" },
  SYR: { ja: "シリア", iso2: "sy" },
  TJK: { ja: "タジキスタン", iso2: "tj" },
  TZA: { ja: "タンザニア", iso2: "tz" },
  THA: { ja: "タイ", iso2: "th", wp: "タイ王国" },
  TLS: { ja: "東ティモール", iso2: "tl" },
  TGO: { ja: "トーゴ", iso2: "tg" },
  TTO: { ja: "トリニダード・トバゴ", iso2: "tt" },
  TUN: { ja: "チュニジア", iso2: "tn" },
  TUR: { ja: "トルコ", iso2: "tr" },
  TKM: { ja: "トルクメニスタン", iso2: "tm" },
  UGA: { ja: "ウガンダ", iso2: "ug" },
  UKR: { ja: "ウクライナ", iso2: "ua" },
  ARE: { ja: "アラブ首長国連邦", iso2: "ae" },
  GBR: { ja: "イギリス", iso2: "gb" },
  USA: { ja: "アメリカ合衆国", iso2: "us" },
  URY: { ja: "ウルグアイ", iso2: "uy" },
  UZB: { ja: "ウズベキスタン", iso2: "uz" },
  VUT: { ja: "バヌアツ", iso2: "vu" },
  VEN: { ja: "ベネズエラ", iso2: "ve" },
  VNM: { ja: "ベトナム", iso2: "vn" },
  YEM: { ja: "イエメン", iso2: "ye" },
  ZMB: { ja: "ザンビア", iso2: "zm" },
  ZWE: { ja: "ジンバブエ", iso2: "zw" },
  PSE: { ja: "パレスチナ", iso2: "ps", wp: "パレスチナ国" },
  ESH: { ja: "西サハラ", iso2: "eh" },
  TWN: { ja: "台湾", iso2: "tw" },
  MKD: { ja: "北マケドニア", iso2: "mk" },
  ABW: { ja: "アルバ", iso2: "aw" },
  HKG: { ja: "香港", iso2: "hk" },
  MAC: { ja: "マカオ", iso2: "mo" },
  NCL: { ja: "ニューカレドニア", iso2: "nc" },
  PYF: { ja: "フランス領ポリネシア", iso2: "pf" },
  FSM: { ja: "ミクロネシア連邦", iso2: "fm" },
  MHL: { ja: "マーシャル諸島", iso2: "mh" },
  PLW: { ja: "パラオ", iso2: "pw" },
  TON: { ja: "トンガ", iso2: "to" },
  WSM: { ja: "サモア", iso2: "ws" },
  TUV: { ja: "ツバル", iso2: "tv" },
  NRU: { ja: "ナウル", iso2: "nr" },
  BMU: { ja: "バミューダ", iso2: "bm" },
  GLP: { ja: "グアドループ", iso2: "gp" },
  GUF: { ja: "フランス領ギアナ", iso2: "gf" },
  MTQ: { ja: "マルティニーク", iso2: "mq" },
  REU: { ja: "レユニオン", iso2: "re" },
  CUW: { ja: "キュラソー", iso2: "cw", wp: "キュラソー島" },
  CYM: { ja: "ケイマン諸島", iso2: "ky" },
  ASM: { ja: "アメリカ領サモア", iso2: "as" },
  GUM: { ja: "グアム", iso2: "gu" },
  MNP: { ja: "北マリアナ諸島", iso2: "mp" },
  PRI: { ja: "プエルトリコ", iso2: "pr" },
  VIR: { ja: "アメリカ領ヴァージン諸島", iso2: "vi" },
};

// 表示名（日本語があれば日本語、無ければ英語名にフォールバック）
export function countryName(iso3: string | null, fallback: string): string {
  if (!iso3) return fallback;
  return COUNTRY_INFO[iso3]?.ja ?? fallback;
}
